#!/usr/bin/env python3
"""
Quick Telegram Setup Guide - Non-Interactive
Shows you exactly how to set up Telegram alerts step by step.
"""

def show_telegram_bot_creation():
    print("📱 Telegram Bot Creation Guide")
    print("=" * 40)
    print()
    print("🤖 Step 1: Create Your Telegram Bot")
    print("-" * 35)
    print("1. Open Telegram app on your phone or computer")
    print("2. Search for '@BotFather' and start a chat")
    print("3. Send this command: /newbot")
    print("4. BotFather will ask for a name - enter: MyTradingBot")
    print("5. BotFather will ask for a username - enter: mytradingalerts_bot")
    print("   (Must end with 'bot' and be unique)")
    print("6. BotFather will give you a token like:")
    print("   📋 123456789:ABCdefGHIjklMNOpqrsTUVwxyz")
    print("7. 🔑 COPY THIS TOKEN - you'll need it!")

def show_chat_id_instructions():
    print("\n💬 Step 2: Get Your Chat ID")
    print("-" * 30)
    print("1. Click the link BotFather provides to start a chat with your bot")
    print("2. Send any message to your bot (example: 'Hello')")
    print("3. To find your chat ID, visit this URL in your browser:")
    print("   https://api.telegram.org/bot[YOUR_BOT_TOKEN]/getUpdates")
    print("   (Replace [YOUR_BOT_TOKEN] with your actual token)")
    print("4. Look for 'chat':{'id': YOUR_CHAT_ID}")
    print("5. 📋 COPY the chat ID number")

def show_config_template():
    print("\n⚙️ Step 3: Create Configuration")
    print("-" * 35)
    print("Create a file called 'my_telegram_config.py' with this content:")
    print()
    print("```python")
    print("#!/usr/bin/env python3")
    print('"""')
    print("My Telegram Alert Configuration")
    print('"""')
    print()
    print("# Replace these with your actual credentials")
    print('BOT_TOKEN = "123456789:ABCdefGHIjklMNOpqrsTUVwxyz"  # Your bot token')
    print('CHAT_ID = "123456789"  # Your chat ID')
    print()
    print("# Telegram alert configuration")
    print("TELEGRAM_CONFIG = {")
    print('    "alerts_enabled": True,')
    print('    "alert_on_decisions": ["BUY", "SELL"],')
    print('    "notification_handlers": {')
    print('        "telegram": {')
    print('            "enabled": True,')
    print('            "bot_token": BOT_TOKEN,')
    print('            "chat_id": CHAT_ID,')
    print('            "parse_mode": "Markdown",')
    print('            "disable_notification": False,')
    print("        }")
    print("    }")
    print("}")
    print("```")

def show_test_script():
    print("\n🧪 Step 4: Test Your Setup")
    print("-" * 30)
    print("Create a file called 'test_my_telegram.py' with this content:")
    print()
    print("```python")
    print("#!/usr/bin/env python3")
    print("import requests")
    print("from datetime import datetime")
    print()
    print("# Your credentials (replace with actual values)")
    print('bot_token = "123456789:ABCdefGHIjklMNOpqrsTUVwxyz"')
    print('chat_id = "123456789"')
    print()
    print("def test_telegram():")
    print('    print("🧪 Testing Telegram Bot...")')
    print("    ")
    print("    # Test message")
    print('    message = "🚨 *Test Alert*\\n\\n📊 Your trading bot is working!"')
    print("    ")
    print('    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"')
    print("    payload = {")
    print('        "chat_id": chat_id,')
    print('        "text": message,')
    print('        "parse_mode": "Markdown"')
    print("    }")
    print("    ")
    print("    try:")
    print("        response = requests.post(url, json=payload)")
    print("        if response.status_code == 200:")
    print('            print("✅ Test message sent! Check your Telegram")')
    print("        else:")
    print('            print(f"❌ Error: {response.text}")')
    print("    except Exception as e:")
    print('        print(f"❌ Failed: {e}")')
    print()
    print('if __name__ == "__main__":')
    print("    test_telegram()")
    print("```")

def show_integration_steps():
    print("\n🔗 Step 5: Integration with Trading System")
    print("-" * 45)
    print("1. Save your configuration file as 'my_telegram_config.py'")
    print("2. Test it with: python3 test_my_telegram.py")
    print("3. Once working, update your main trading configuration:")
    print()
    print("In your main trading script, use:")
    print("```python")
    print("from my_telegram_config import TELEGRAM_CONFIG")
    print("config['alert_config'] = TELEGRAM_CONFIG")
    print("```")

def show_troubleshooting():
    print("\n🔧 Common Issues & Solutions")
    print("-" * 35)
    print("❌ 'Bot token not found'")
    print("   → Make sure you copied the full token from BotFather")
    print("   → Token should be about 45 characters long")
    print()
    print("❌ 'Chat not found'")
    print("   → Send a message to your bot first")
    print("   → Check the getUpdates URL returns data")
    print()
    print("❌ 'Unauthorized'")
    print("   → Verify bot token is correct")
    print("   → Make sure you didn't delete the bot")
    print()
    print("❌ 'Bad Request'")
    print("   → Check your chat ID is a number")
    print("   → Verify message format is correct")

def show_sample_alert():
    print("\n📱 What Your Alerts Will Look Like")
    print("-" * 40)
    print("🟢📈 *BUY Signal*")
    print()
    print("📊 *Ticker:* `AAPL`")
    print("📅 *Date:* 2025-06-27")
    print("💭 *Summary:* Strong bullish signals detected")
    print()
    print("📈 *Analysis Details:*")
    print("🎯 Target: `$185.00`")
    print("🛑 Stop Loss: `$165.00`")
    print("📊 Confidence: `85%`")
    print("🔧 Technical: RSI oversold, MACD bullish crossover")
    print()
    print("⏰ *Alert Time:* 14:30:22 UTC")
    print("🤖 *Trading Agents Alert System*")

def main():
    print("📱 Telegram Alert Setup - Step by Step Guide")
    print("=" * 55)
    print("This guide will help you set up Telegram alerts manually.")
    print()
    
    show_telegram_bot_creation()
    show_chat_id_instructions()
    show_config_template()
    show_test_script()
    show_integration_steps()
    show_troubleshooting()
    show_sample_alert()
    
    print("\n🎉 Setup Complete!")
    print("=" * 20)
    print("Once you've followed all steps:")
    print("1. ✅ Created your bot with BotFather")
    print("2. ✅ Got your bot token and chat ID")
    print("3. ✅ Created and tested configuration")
    print("4. ✅ Integrated with trading system")
    print()
    print("You'll receive instant Telegram alerts for all trading signals! 🚀")
    
    print("\n📋 Quick Links:")
    print("• BotFather: https://t.me/botfather")
    print("• Test your bot: python3 test_my_telegram.py")
    print("• Full system test: python3 test_personal_alerts.py")

if __name__ == "__main__":
    main()